// <auto-generated />
using System;
using FulfillmentCenter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FulfillmentCenter.Migrations
{
    [DbContext(typeof(FulfillmentCenterDbContext))]
    partial class FulfillmentCenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FulfillmentCenter.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CustomerName = "Contoso Ltd",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CustomerName = "Northwind Traders",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CustomerName = "Adventure Works",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.DistributionCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DistributionCenters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            City = "Prague",
                            IsDeleted = false,
                            Name = "Central Hub"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            City = "Brno",
                            IsDeleted = false,
                            Name = "North Depot"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            City = "Bratislava",
                            IsDeleted = false,
                            Name = "South Warehouse"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            City = "Vienna",
                            IsDeleted = false,
                            Name = "East Logistics Center"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            City = "Budapest",
                            IsDeleted = false,
                            Name = "West Distribution Point"
                        });
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DistributionCenterId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistributionCenterId");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DistributionCenterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            DistributionCenterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Quantity = 120
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DistributionCenterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            DistributionCenterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Quantity = 75
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            DistributionCenterId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsDeleted = false,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Quantity = 200
                        });
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Product", b =>
                {
                    b.Property<string>("SKU")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("SKU");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            SKU = "SKU-001",
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsDeleted = false,
                            Name = "Product A",
                            Weight = 1.5m
                        },
                        new
                        {
                            SKU = "SKU-002",
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsDeleted = false,
                            Name = "Product B",
                            Weight = 2.0m
                        });
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DistributionCenterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EstimatedDelivery")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ShippedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DistributionCenterId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Inventory", b =>
                {
                    b.HasOne("FulfillmentCenter.Entities.DistributionCenter", "DistributionCenter")
                        .WithMany("Inventories")
                        .HasForeignKey("DistributionCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FulfillmentCenter.Entities.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionCenter");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Order", b =>
                {
                    b.HasOne("FulfillmentCenter.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.OrderItem", b =>
                {
                    b.HasOne("FulfillmentCenter.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FulfillmentCenter.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Shipment", b =>
                {
                    b.HasOne("FulfillmentCenter.Entities.DistributionCenter", "DistributionCenter")
                        .WithMany("Shipments")
                        .HasForeignKey("DistributionCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FulfillmentCenter.Entities.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("FulfillmentCenter.Entities.Shipment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionCenter");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.DistributionCenter", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("FulfillmentCenter.Entities.Product", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
